sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - docker docker build . --file Dockerfile --tag covidmutants:latest
      - docker run covidmutants:latest -forward TATgCCATTAgTgCAAAgAATAgAgCTCgCAC -reverse GTAATTGGAAcAAGcAAATTcTATGGTGGTTG -amplicon TATGCCATTAGTGCAAAGAATAGAGCTCGCACCGTAGCTGGTGTCTCTATCTGTAGTACTATGACCAATAGACAGTTTCATCAAAAATTATTGAAATCAATAGCCGCCACTAGAGGAGCTACTGTAGTAATTGGAACAAGCAAATTCTATGGTGGTTG -v -fasta test.fa.gz
